class AppStrings {
  static const apiKey = "AIzaSyBlDiz9uyftnzTJHC7WzOBsmGwIrvvTC4M",
      autoCompleteUrl =
          "https://maps.googleapis.com/maps/api/place/autocomplete/json",
      placeDetailsUrl =
          "https://maps.googleapis.com/maps/api/place/details/json",
      helloNiceToMeetYou = 'Hello, nice to meet you!',
      getMovingWithGreenTaxi = 'Get moving with Green Taxi',
      pleaseEnterYourPhoneErr = "Please Enter your Phone Number",
      phoneNumberDigitErr = "The phone number must be a 10-digit ",
      enterMobileNumber = 'Enter your mobile number',
      byCreating = 'By creating an account, you agree to our',
      termsOfService = 'Terms of Service',
      fieldRequired = 'This field is required',
      goodMorning = 'Good Morning.  ',
      whereAreYouGoing = 'Where are you going?',
      of = 'of',
      name = 'Name',
      homeAddress = 'Home Address',
      businessAddress = 'Business Address',
      shoppingCenter = 'Shopping Center',
      submit = 'Submit',
      and = ' and ',
      profileSettings = 'Profile Settings',
      myProfile = 'My Profile',
      privacyPolicy = 'Privacy Policy',
      phoneVerification = 'Phone Verification',
      enterOtp = 'Enter your OTP code below',
      resendCode = 'Resend code in',
      searchForDestination = 'Search for a destination',
      paymentHistory = 'Payment History',
      rideHistory = 'Ride History',
      inviteFriends = 'Invite Friends',
      promoCodes = 'Promo Codes',
      settings = 'Settings',
      logOut = "Log Out",
      support = 'Support',
      doMore = 'Do more',
      getFoodDelivery = 'Get food delivery',
      makeMoneyDriving = 'Make money driving',
      rateUsOnStore = 'Rate us on store',
      seconds = 'seconds';
}
