// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDNh3s_PI5q5Jzs4vm4XsgqsPipPFX3PQ',
    appId: '1:85301610512:web:e733a7cb4c2e2ff2726295',
    messagingSenderId: '85301610512',
    projectId: 'green-taxi-8e8c1',
    authDomain: 'green-taxi-8e8c1.firebaseapp.com',
    storageBucket: 'green-taxi-8e8c1.appspot.com',
    measurementId: 'G-DTVR7TH7K5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDESBIQj5LGHqJkJoFd4LylnhFy9A7-ykg',
    appId: '1:85301610512:android:093f34cf17b3ece3726295',
    messagingSenderId: '85301610512',
    projectId: 'green-taxi-8e8c1',
    storageBucket: 'green-taxi-8e8c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFYk_KJ3ySP8qqDJ4dQuZwyAICICXcwz8',
    appId: '1:85301610512:ios:bec371cc67f0309b726295',
    messagingSenderId: '85301610512',
    projectId: 'green-taxi-8e8c1',
    storageBucket: 'green-taxi-8e8c1.appspot.com',
    iosBundleId: 'com.example.greenTaxi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFYk_KJ3ySP8qqDJ4dQuZwyAICICXcwz8',
    appId: '1:85301610512:ios:b1316a050a5114b9726295',
    messagingSenderId: '85301610512',
    projectId: 'green-taxi-8e8c1',
    storageBucket: 'green-taxi-8e8c1.appspot.com',
    iosBundleId: 'com.example.greenTaxi.RunnerTests',
  );
}
